default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RoR_group_project_production

test:
  <<: *default
  database: RoR_group_project_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: RoR_group_project_production
  url: <%= ENV['DATABASE_URL'] %>